from enum import Flag, auto
from kgegrok.data import constants
from kgegrok.data import statstools

MEAN_RECIPROCAL_RANK_FEATURE_KEY = 'mean_reciprocal_rank'
MEAN_FILTERED_RECIPROCAL_RANK_FEATURE_KEY = 'mean_filtered_reciprocal_rank'
MEAN_RANK_FEATURE_KEY = 'mean_rank'
MEAN_FILTERED_RANK_FEATURE_KEY = 'mean_filtered_rank'
HITS_FEATURE_PREFIX = 'hits'
FILTERED_HITS_FEATURE_PREFIX = 'hits_filtered'
LOSS_FEATURE_KEY = 'loss'


class LinkPredictionStatistics(Flag):
  MEAN_RECIPROCAL_RANK = auto()
  MEAN_FILTERED_RECIPROCAL_RANK = auto()
  MEAN_RANK = auto()
  MEAN_FILTERED_RANK = auto()
  MEAN_RANKS = MEAN_RECIPROCAL_RANK | MEAN_RANK
  MEAN_FILTERED_RANKS = MEAN_FILTERED_RECIPROCAL_RANK | MEAN_FILTERED_RANK
  ALL_RANKS = MEAN_RANKS | MEAN_FILTERED_RANKS
  HITS = auto()
  HITS_FILTERED = auto()
  ALL_HITS = HITS | HITS_FILTERED
  DEFAULT = HITS_FILTERED | MEAN_FILTERED_RECIPROCAL_RANK
  ALL = ALL_RANKS | ALL_HITS


class StatisticsDimension(Flag):
  SEPERATE_ENTITY = auto()
  COMBINED_ENTITY = auto()
  RELATION = auto()
  DEFAULT = COMBINED_ENTITY | RELATION
  ALL = SEPERATE_ENTITY | RELATION
